# Generated by Django 2.2.4 on 2019-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Units', '0002_auto_20190818_1355'),
        ('Units', '0002_auto_20190817_1656'),
    ]

    operations = [
    ]
