# Generated by Django 2.2.4 on 2019-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Units', '0002_auto_20190812_2333'),
        ('Products', '0003_auto_20190812_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='units_of_measure',
        ),
        migrations.AddField(
            model_name='product',
            name='units_of_measure',
            field=models.ManyToManyField(null=True, to='Units.Unit'),
        ),
    ]
