# Generated by Django 2.2.4 on 2019-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('uid', models.CharField(max_length=60)),
                ('fcm_id', models.CharField(max_length=70)),
            ],
        ),
    ]
