# Generated by Django 2.2.4 on 2019-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_auto_20190820_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fcm_id',
            field=models.CharField(max_length=512),
        ),
    ]
