# Generated by Django 2.2.4 on 2019-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_auto_20190820_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fcm_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
