# Generated by Django 2.2.4 on 2019-09-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabourServices',
            new_name='LabourService',
        ),
    ]
