# Generated by Django 2.2.4 on 2019-08-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number_of_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_bids', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('price', models.IntegerField()),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FPackage', to='Packages.Period')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('searches', models.BooleanField()),
                ('total_bid_placed', models.IntegerField()),
                ('broadCastAbility', models.BooleanField()),
                ('price', models.IntegerField()),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BPackage', to='Packages.Period')),
            ],
        ),
    ]
