# Generated by Django 2.2.4 on 2019-08-14 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Units', '0001_initial'),
        ('Buyer', '0002_auto_20190814_2340'),
        ('County', '0001_initial'),
        ('Farm', '0003_auto_20190814_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='Buyer.Buyer')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='County.County')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='Products.Product')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Units.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Units.Unit')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='County.County')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Farm.Farm')),
            ],
        ),
    ]
