# Generated by Django 2.2.4 on 2019-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
