# Generated by Django 2.2.4 on 2019-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_auto_20190814_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='valid',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='package_update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
