# Generated by Django 2.2.4 on 2019-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
