# Generated by Django 2.2.4 on 2019-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20190814_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='packages_buying_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
